export type Song = {
  id: number;
  title: string;
  artist: string;
  artwork: string;
  url: string;
  preview: string | null;
};
export type User = {
  id: string;
  username: string;
  name: string;
  bio: string;
  avatar: string | null;
  interests: string[];
  song: Song | null;
  accent: string;
  private: number;
  email?: string;
  messages?: string;
  receipts?: number;
  activity?: number;
  language?: "en" | "ar";
  theme?: "system" | "light" | "dark";
  onboarded?: number;
  notifications?: string[];
  following?: string | null;
  shared?: string[];
  followers?: number;
};
export type Post = {
  id: string;
  author: string;
  username: string;
  name: string;
  avatar: string | null;
  body: string;
  image: string | null;
  song: Song | null;
  audience: string;
  circleId: string | null;
  kind: string;
  mood: string | null;
  pinned: number;
  expires: number | null;
  created: number;
  updated: number | null;
  likes?: number;
  liked?: number;
  comments?: number;
  saved?: number;
};
export type Circle = {
  id: string;
  owner: string;
  name: string;
  description: string;
  rules: string;
  interest: string;
  private: number;
  status: string | null;
  role: string | null;
  members: number;
};
export type Conversation = {
  id: string;
  a: string;
  b: string;
  initiator: string;
  status: string;
  name: string;
  username: string;
  avatar: string | null;
  other: string;
  lastBody: string | null;
  lastAt: number | null;
  unread: number;
  draft: string | null;
  muted: number | null;
};
export type Message = {
  id: string;
  conversationId: string;
  sender: string;
  body: string;
  media: string | null;
  replyTo: string | null;
  created: number;
  delivered: number | null;
  read: number | null;
  reactions?: { userId: string; emoji: string }[];
  localState?: "pending" | "failed";
};
export type Notice = {
  id: string;
  actor: string;
  name: string;
  username: string;
  avatar: string | null;
  type: string;
  target: string;
  read: number | null;
  created: number;
};
export type Cursor = { before: number; cursor: string; score?: number } | null;
